# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceType', models.CharField(choices=[('Games', 'Games'), ('Techniques', 'Techniques'), ('Articles', 'Articles')], max_length=200)),
                ('resourceTitle', models.CharField(max_length=200)),
                ('techniqueUsed', models.CharField(max_length=200)),
                ('techniqueDescription', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='')),
            ],
        ),
    ]
