# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algodetails',
            name='author',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='algodetails',
            name='document',
            field=models.FileField(upload_to='res/'),
        ),
    ]
