# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_auto_20180305_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='algodetails',
            name='algorithmUsed',
            field=models.CharField(choices=[('Artificial Neural Networks', 'Artificial Neural Networks'), ('Naive Based Classifier', 'Naive Based Classifier'), ('Case Based Reasoning', 'Case Based Reasoning'), ('Support Vector Machines', 'Support Vector Machines'), ('Decision Trees', 'Decision Trees'), ('Fuzzy Logic', 'Fuzzy Logic'), ('Markov Systems', 'Markov Systems'), ('Goal Oriented Behavior', 'Goal Oriented Behavior'), ('Rule-based Systems', 'Rule-based Systems'), ('Finate-State Machines', 'Finate-State Machines')], default='a', max_length=200),
            preserve_default=False,
        ),
    ]
