# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0003_algodetails_algorithmused'),
    ]

    operations = [
        migrations.AddField(
            model_name='algodetails',
            name='requestStatus',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AddField(
            model_name='algodetails',
            name='userId',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
